services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopping-api
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    container_name: shopping-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 60s
      timeout: 5s
      retries: 5
