// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_input.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dto "github.com/LeoTwins/go-clean-architecture/internal/usecase/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockITransactionUsecase is a mock of ITransactionUsecase interface.
type MockITransactionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockITransactionUsecaseMockRecorder
}

// MockITransactionUsecaseMockRecorder is the mock recorder for MockITransactionUsecase.
type MockITransactionUsecaseMockRecorder struct {
	mock *MockITransactionUsecase
}

// NewMockITransactionUsecase creates a new mock instance.
func NewMockITransactionUsecase(ctrl *gomock.Controller) *MockITransactionUsecase {
	mock := &MockITransactionUsecase{ctrl: ctrl}
	mock.recorder = &MockITransactionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITransactionUsecase) EXPECT() *MockITransactionUsecaseMockRecorder {
	return m.recorder
}

// FindByAccountID mocks base method.
func (m *MockITransactionUsecase) FindByAccountID(accountID uint) ([]*dto.TransactionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAccountID", accountID)
	ret0, _ := ret[0].([]*dto.TransactionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAccountID indicates an expected call of FindByAccountID.
func (mr *MockITransactionUsecaseMockRecorder) FindByAccountID(accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAccountID", reflect.TypeOf((*MockITransactionUsecase)(nil).FindByAccountID), accountID)
}

// FindByID mocks base method.
func (m *MockITransactionUsecase) FindByID(id uint) (*dto.TransactionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*dto.TransactionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockITransactionUsecaseMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockITransactionUsecase)(nil).FindByID), id)
}
